# Data Load and Cleaning
- Load data
- Remove unnecessary column
- Data Type change
- Duplicate
- Null Value
- Save cleaned data

In [1]:
# Imports

import numpy as np
import pandas as pd

In [2]:
# Load Data

data = pd.read_csv(r"C:\Users\Hp\Desktop\BIA\DATA SCIENCE PROJECTS\ds_project_1\CAPSTONE PROJECT\Data\Fraud_Analysis_Dataset.csv")
data.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud
0,1,TRANSFER,181.0,C1305486145,181.0,0.0,C553264065,0.0,0.0,1
1,1,CASH_OUT,181.0,C840083671,181.0,0.0,C38997010,21182.0,0.0,1
2,1,TRANSFER,2806.0,C1420196421,2806.0,0.0,C972765878,0.0,0.0,1
3,1,CASH_OUT,2806.0,C2101527076,2806.0,0.0,C1007251739,26202.0,0.0,1
4,1,TRANSFER,20128.0,C137533655,20128.0,0.0,C1848415041,0.0,0.0,1

In [3]:
# Create back-up
df = data.copy()

In [4]:
# Meta-data
print("No. of rows", df.shape[0])
print("No. of columns", df.shape[1])
all_columns = df.columns.to_list()
num_columns = df.select_dtypes(include = "number").columns.to_list()
cat_columns = df.select_dtypes(include = "object").columns.to_list()
print("All columns: \n", all_columns)
print("\n Numeric Columns: \n", num_columns)
print("\n Categorical Columns: \n", cat_columns)
print ("\n Data Type: \n", df.dtypes)
print("\n Info: \n")
df.info()

No. of rows 11142
No. of columns 10
All columns:
 ['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig', 'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud']

 Numeric Columns:
 ['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest', 'isFraud']

 Categorical Columns:
 ['type', 'nameOrig', 'nameDest']

 Data Type:
 step                int64
type                  str
amount            float64
nameOrig              str
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest              str
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
dtype: object

 Info:

C:\Users\Hp\AppData\Local\Temp\ipykernel_23040\3215183985.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_columns = df.select_dtypes(include = "object").columns.to_list()

<class 'pandas.DataFrame'>
RangeIndex: 11142 entries, 0 to 11141
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   step            11142 non-null  int64
 1   type            11142 non-null  str
 2   amount          11142 non-null  float64
 3   nameOrig        11142 non-null  str
 4   oldbalanceOrg   11142 non-null  float64
 5   newbalanceOrig  11142 non-null  float64
 6   nameDest        11142 non-null  str
 7   oldbalanceDest  11142 non-null  float64
 8   newbalanceDest  11142 non-null  float64
 9   isFraud         11142 non-null  int64
dtypes: float64(5), int64(2), str(3)
memory usage: 1.1 MB

In [5]:
# Duplicate 
print("Duplicate count: ", df.duplicated().sum())
print("Duplicate Columns: \n")
df[df.duplicated()]

Duplicate count:  0
Duplicate Columns:

Empty DataFrame
Columns: [step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig, nameDest, oldbalanceDest, newbalanceDest, isFraud]
Index: []

In [6]:
# Null value check
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
dtype: int64

In [7]:
# Target distribution

print("Target counts:\n", df["isFraud"].value_counts())
print("\nTarget distribution (%):\n", (df["isFraud"].value_counts(normalize=True) * 100).round(2))

Target counts:
 isFraud
0    10000
1     1142
Name: count, dtype: int64

Target distribution (%):
 isFraud
0    89.75
1    10.25
Name: proportion, dtype: float64

In [8]:
# Remove unnecessary columns

df.drop(columns=["nameOrig", "nameDest"], inplace=True)
df.head(2)

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
0,1,TRANSFER,181.0,181.0,0.0,0.0,0.0,1
1,1,CASH_OUT,181.0,181.0,0.0,21182.0,0.0,1

In [9]:
# Final structure check

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11142 entries, 0 to 11141
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   step            11142 non-null  int64
 1   type            11142 non-null  str
 2   amount          11142 non-null  float64
 3   oldbalanceOrg   11142 non-null  float64
 4   newbalanceOrig  11142 non-null  float64
 5   oldbalanceDest  11142 non-null  float64
 6   newbalanceDest  11142 non-null  float64
 7   isFraud         11142 non-null  int64
dtypes: float64(5), int64(2), str(1)
memory usage: 775.3 KB

In [11]:
# Save cleaned data

file_name = "cleaned_fraud_data.csv"
df.to_csv(file_name, index=False)
print(f"Cleaned data saved as: {file_name}")

Cleaned data saved as: cleaned_fraud_data.csv